### ISSUE TITLE
Provide a Docker image that includes pydeface

### ISSUE THREAD

**Issue by SamGuay** [UNFmontreal/Dcm2Bids#272]
As [mentioned on Neurostars](https://neurostars.org/t/using-pydeface-within-the-dcm2bids-config-file/26048/12), some people would like to use dcm2bids Docker container with pydeface.

To keep the image size to a minimum, I think we should take advantage of the solution mentioned in [pydeface's #54](https://github.com/poldracklab/pydeface/issues/54).

I think if we go ahead and provide such container, it needs a distinctive tag and `:latest` should default to dcm2bids only.

**Comment by mateuszpawlik** [comment]
If it helps, [here's the resources for the image](https://gitlab.com/ccns/neurocog/neurodataops/anc/pipelines/containers/-/tree/main/anc-data-acquisition?ref_type=heads) I mentioned in https://github.com/poldracklab/pydeface/issues/54. I collected the flirt dependencies by trying to build it from sources.

**Update:** Using Conda is a better way now for installing FSL tools. See @SamGuay's comment below.

**Comment by SamGuay** [comment]
Thanks @mateuszpawlik for the info and the work towards the PR on pydeface to enable only flirt! I think we could follow a similar way of building a relatively small image using your approach in https://gitlab.com/ccns/neurocog/neurodataops/anc/containers/fsl-bet-flirt for which we can use the env below. Then we can shrink the image using [conda-pack](https://pythonspeed.com/articles/conda-docker-image-size/).

2 caveats still though: 
1. pydeface 2.0.3 with [PR#56](https://github.com/poldracklab/pydeface/tree/devel) is only available on the devel branch for now.
2. Need to set FSLDIR="something random" because pydeface 2.0.3 [initially checks for that env](https://github.com/poldracklab/pydeface/blob/cd0bebd73e842b5a651766202ca9976f9fef9b9f/pydeface/utils.py#L27-L30) and triggers an error message if it is not set. However `flirt` runs without the `$FSLDIR` within a conda env..

```yaml
name: dcm2bids-docker-env
channels:
  - conda-forge
  - https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/public/
dependencies:
  - dcm2bids
  - dcm2niix
  - fsl-flirt
  - bids-validator
  - pip
  - pip:
    - git+https://github.com/poldracklab/pydeface.git@devel # since only v2.0.2 (on pypi)
```
